### ISSUE TITLE
Panic on tasks without results

### ISSUE THREAD

**Issue by egorsmkv** [RichardKnop/machinery#109]
I create simple task without result, example:

```go
func TaskName(arg string) error {
	// task body
	return nil
}
```

But server panic after I request this task:

```
machinery: redis.go:211: Received new message: {"UUID":"task_6d8de9e3-3548-4247-8088-2196db717fb3","Name":"TaskName","RoutingKey":"","GroupUUID":"","GroupTaskCount":0,"Args":[{"Type":"string","Value":"oloololol"}],"Headers":null,"Immutable":false,"OnSuccess":null,"OnError":null,"ChordCallback":null}
machinery: worker.go:245: goroutine 7 [running]:
runtime/debug.Stack(0x7009c0, 0x6fd540, 0xc42000c130)
	/home/egor/Tools/GoRoot/src/runtime/debug/stack.go:24 +0x79
egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1.TryCall.func1(0xc42004bdd0)
	/home/egor/Tools/GoPath/src/egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/worker.go:245 +0x104
panic(0x6fd540, 0xc42000c130)
	/home/egor/Tools/GoRoot/src/runtime/panic.go:458 +0x243
egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1.TryCall(0x6f0e40, 0x779770, 0x13, 0xc4200112e0, 0x1, 0x1, 0xc420011420, 0x1, 0x1, 0x8b2ea0, ...)
	/home/egor/Tools/GoPath/src/egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/worker.go:253 +0x237
egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc420010980, 0xc4200aa0b0, 0x100, 0x6f6480)
	/home/egor/Tools/GoPath/src/egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/worker.go:91 +0x45f
egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/brokers.(*RedisBroker).consumeOne(0xc4200883c0, 0xc42000a700, 0x100, 0x100, 0x8b1ba0, 0xc420010980)
	/home/egor/Tools/GoPath/src/egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.go:219 +0x1fc
egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/brokers.(*RedisBroker).consume.func1(0xc4200883c0, 0xc42000a700, 0x100, 0x100, 0x8b1ba0, 0xc420010980)
	/home/egor/Tools/GoPath/src/egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.go:234 +0x5d
created by egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/brokers.(*RedisBroker).consume
	/home/egor/Tools/GoPath/src/egorsmkv/hidden-name/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.go:235 +0x17d
machinery: worker.go:188: Failed processing task_6d8de9e3-3548-4247-8088-2196db717fb3. Error = runtime error: index out of range
```

**Comment by saggit** [comment]
Yes, try to return (string, error) in your task define.

**Comment by RichardKnop** [comment]
Yes this is currently an issue. Tasks that don't return an argument back but just error will fail.

You need to return some value + error from tasks. This might not be too difficult to refactor.

This function will probably need to become more robust:

https://github.com/RichardKnop/machinery/blob/master/v1/worker.go#L231

As currently it makes an assumption that second returned value is an error.

**Comment by RichardKnop** [comment]
@saggit @egorsmkv This should be solved in this pull request:

https://github.com/RichardKnop/machinery/pull/131

**Comment by egorsmkv** [comment]
Thanks, Richard!
