### ISSUE TITLE
runtime problem

### ISSUE THREAD

**Issue by davmaz** [RichardKnop/machinery#119]
Great package -- looks very interesting. But I installed rabbitmq and ran the examples as you've described in the documentation, and it fails with this output:
machinery: worker.go:110: Processed task_2e01a458-61ec-40f2-968e-775c12fa3b57. Result = 68
machinery: amqp.go:159: Received new message: {"UUID":"task_125cbb34-be07-4f3d-9fb4-288cad6c1971","Name":"panic_task","RoutingKey":"","GroupUUID":"","GroupTaskCount":0,"Args":null,"Headers":null,"Immutable":false,"OnSuccess":null,"OnError":null,"ChordCallback":null}
machinery: worker.go:263: goroutine 294 [running]:
runtime/debug.Stack(0x750de0, 0x746200, 0xc420326bf0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/RichardKnop/machinery/v1.TryCall.func1(0xc4201f5b30)
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/v1/worker.go:263 +0xf5
panic(0x746200, 0xc420326bf0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/RichardKnop/machinery/examples/tasks.PanicTask(0x0, 0x0, 0x0, 0x0)
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/examples/tasks/tasks.go:27 +0x78
reflect.Value.call(0x73b1c0, 0x7b8bc0, 0x13, 0x7a63e6, 0x4, 0x95df80, 0x0, 0x0, 0xc4201f5a98, 0xc4201f5a90, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x73b1c0, 0x7b8bc0, 0x13, 0x95df80, 0x0, 0x0, 0x0, 0x0, 0xc42018b3c0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/RichardKnop/machinery/v1.TryCall(0x73b1c0, 0x7b8bc0, 0x13, 0x95df80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x921e00, ...)
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/v1/worker.go:267 +0xf1
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc42000c780, 0xc42001ba20, 0xa, 0x746401)
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/v1/worker.go:91 +0x42c
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consumeOne(0xc42001c600, 0x924f00, 0xc42000a700, 0x0, 0xc420326070, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:175 +0x25d
github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume.func2(0xc42001c600, 0xc4200b0a00, 0x921e80, 0xc42000c780, 0xc4200e81e0, 0x0, 0xc4200e8180)
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:207 +0x9f
created by github.com/RichardKnop/machinery/v1/brokers.(*AMQPBroker).consume
	/opt/Projects/Golang/src/github.com/RichardKnop/machinery/v1/brokers/amqp.go:212 +0x270
machinery: worker.go:206: Failed processing task_125cbb34-be07-4f3d-9fb4-288cad6c1971. Error = oops

**Comment by davmaz** [comment]
Sorry for the bad issue report. I didn't have a backend running.
