### ISSUE TITLE
Parallel executing is not supported when using 'eager' broker  and backend?

### ISSUE THREAD

**Issue by steven-zou** [RichardKnop/machinery#234]
**config.yaml:**
```
broker: 'eager'
default_queue: machinery_tasks
result_backend: 'eager'
```
When executing group/chord tasks, runtime error occurred:
```
concurrent map writes

goroutine 22 [running]:
runtime.throw(0x15e6701, 0x15)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc420055ca8 sp=0xc420055c88 pc=0x102bec5
runtime.mapassign_faststr(0x1549680, 0xc420186150, 0xc42001cb70, 0x29, 0x81)
	/usr/local/go/src/runtime/hashmap_fast.go:861 +0x4da fp=0xc420055d28 sp=0xc420055ca8 pc=0x100eb0a
github.com/RichardKnop/machinery/v1/backends.(*EagerBackend).updateState(0xc420047570, 0xc420083040, 0x0, 0xc420095440)
	/Users/szou/VMware/Projects/Go/src/github.com/RichardKnop/machinery/v1/backends/eager.go:196 +0x117 fp=0xc420055d98 sp=0xc420055d28 pc=0x131d987

```

Checked code line 196 in **github.com/RichardKnop/machinery/v1/backends/eager.go**, seems no any sync lock way used in the following method:
```
func (b *EagerBackend) updateState(s *tasks.TaskState) error
```

**Is it worked as design? 'eager' does not support parallel executing?** Looking forward to the answer. @RichardKnop  Thanks!

**Comment by RichardKnop** [comment]
@steven-zou Eager mode is only present for testing purposes. It was not designed to really be used in real scenarios. But yes, this is a bug which could be solved.
