### ISSUE TITLE
Always error when using chain

### ISSUE THREAD

**Issue by herpiko** [RichardKnop/machinery#339]
Hi,

I've these simple two workers that that has its own task. These tasks only print somestring. When I use chain to run these tasks sequentially, this error occured in worker side. I've change the broker and result backend to other options, but the erorr still persist.

The error gone if I just put only one task to the chain.

```
INFO: 2018/09/21 22:20:13 worker.go:44 Launching a worker with the following settings:
INFO: 2018/09/21 22:20:13 worker.go:45 - Broker: amqp://guest:guest@localhost:5672/
INFO: 2018/09/21 22:20:13 worker.go:47 - DefaultQueue: irgsh_tasks
INFO: 2018/09/21 22:20:13 worker.go:51 - ResultBackend: amqp://guest:guest@localhost:5672/
INFO: 2018/09/21 22:20:13 worker.go:53 - AMQP: machinery_exchange
INFO: 2018/09/21 22:20:13 worker.go:54   - Exchange: machinery_exchange
INFO: 2018/09/21 22:20:13 worker.go:55   - ExchangeType: direct
INFO: 2018/09/21 22:20:13 worker.go:56   - BindingKey: machinery_task
INFO: 2018/09/21 22:20:13 worker.go:57   - PrefetchCount: 0
INFO: 2018/09/21 22:20:13 amqp.go:76 [*] Waiting for messages. To exit press CTRL+C
INFO: 2018/09/21 22:20:17 amqp.go:237 Received new message: {"UUID":"task_aa0eb9bb-3aa5-4855-ba24-574fe7734a71","Name":"build","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"string","Value":"inkscape"},{"Name":"","Type":"string","Value":"/blankon/pool/main/i/"}],"Headers":null,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null}
ERROR: 2018/09/21 22:20:17 task.go:86 goroutine 13 [running]:
runtime/debug.Stack(0xd360e8, 0xc4201c6080, 0x2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call.func1(0xc420123b38, 0xc4201da3c0)
	/home/herpiko/go/src/github.com/RichardKnop/machinery/v1/tasks/task.go:86 +0xc1
panic(0x8f5200, 0xa63a20)
	/usr/local/go/src/runtime/panic.go:502 +0x229
reflect.Value.call(0x91e8c0, 0x9ee628, 0x13, 0x9cf79b, 0x4, 0xc4201e6600, 0x2, 0x2, 0xc4201239c8, 0x10, ...)
	/usr/local/go/src/reflect/value.go:367 +0x12c9
reflect.Value.Call(0x91e8c0, 0x9ee628, 0x13, 0xc4201e6600, 0x2, 0x2, 0xc420123a88, 0x411759, 0xc420202210)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call(0xc4201da3c0, 0x0, 0x0, 0x0, 0xa65220, 0xc4201ca140)
	/home/herpiko/go/src/github.com/RichardKnop/machinery/v1/tasks/task.go:98 +0x22c
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc4200727c0, 0xc4201940c0, 0x18, 0xc4200ff4a0)
	/home/herpiko/go/src/github.com/RichardKnop/machinery/v1/worker.go:157 +0x354
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consumeOne(0xc42008e870, 0xa69d60, 0xc42009f8c0, 0x0, 0xc420025120, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/home/herpiko/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:239 +0x43f
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume.func2(0xc42008e870, 0xc4200d1180, 0xa67280, 0xc4200727c0, 0xc42002e660, 0x2, 0xc42002e600)
	/home/herpiko/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:191 +0x8f
created by github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume
	/home/herpiko/go/src/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:190 +0x133

ERROR: 2018/09/21 22:20:17 worker.go:339 Failed processing task_aa0eb9bb-3aa5-4855-ba24-574fe7734a71. Error = reflect: Call with too many input arguments
```

The worker's code (other worker is similiar with different task name) : 
```
➜  builder cat main.go
package main

import (
	"fmt"
	machinery "github.com/RichardKnop/machinery/v1"
	"github.com/RichardKnop/machinery/v1/config"
)

func main() {
	var conf = config.Config{
		Broker:        "amqp://guest:guest@localhost:5672/",
		ResultBackend: "amqp://guest:guest@localhost:5672/",
		DefaultQueue:  "irgsh_tasks",
		AMQP: &config.AMQPConfig{
			Exchange:     "machinery_exchange",
			ExchangeType: "direct",
			BindingKey:   "machinery_task",
		},
	}

	server, err := machinery.NewServer(&conf)
	if err != nil {
		fmt.Println("Could not create server : " + err.Error())
	}

	server.RegisterTask("build", Build)

	worker := server.NewWorker("builder", 2)
	err = worker.Launch()
	if err != nil {
		fmt.Println("Could not launch worker : " + err.Error())
	}
}
➜  builder cat builder.go 
package main

import (
	"errors"
	"fmt"
	"time"
)

func Build(name string) (string, error) {
	fmt.Println("Building : " + name)
	time.Sleep(2 * time.Second)
	if name != "inkscape" {
		return "", errors.New("Only accept soruce of inkscape, not : " + name)
	}
	return name + ".deb", nil
}
➜  builder
```

And the main server's code : 
```
package main

import (
	"fmt"
	machinery "github.com/RichardKnop/machinery/v1"
	"github.com/RichardKnop/machinery/v1/config"
	"github.com/RichardKnop/machinery/v1/tasks"
	"time"
)

func main() {
	var conf = config.Config{
		Broker:        "amqp://guest:guest@localhost:5672/",
		ResultBackend: "amqp://guest:guest@localhost:5672/",
		DefaultQueue:  "irgsh_tasks",
		AMQP: &config.AMQPConfig{
			Exchange:     "machinery_exchange",
			ExchangeType: "direct",
			BindingKey:   "machinery_task",
		},
	}

	server, err := machinery.NewServer(&conf)
	if err != nil {
		fmt.Println("Could not create server : " + err.Error())
	}
	buildSignature := tasks.Signature{
		Name: "build",
		Args: []tasks.Arg{
			{
				Type:  "string",
				Value: "inkscape",
			},
		},
	}
	repoSignature := tasks.Signature{
		Name: "repo",
		Args: []tasks.Arg{
			{
				Type:  "string",
				Value: "inkscape.deb",
			},
		},
	}
	fmt.Println("Sending task")
	chain, _ := tasks.NewChain(&repoSignature, &buildSignature)
	chainAsyncResult, err := server.SendChain(chain)
	if err != nil {
		fmt.Println("Could not create server : " + err.Error())
	}

	results, err := chainAsyncResult.Get(3 * time.Second)
	if err != nil {
		fmt.Println("Failed to get chain async result : " + err.Error())
	}
	for _, result := range results {
		fmt.Println(result.Interface())
	}
}
```

**Comment by herpiko** [comment]
I've tried to run `make ci` on master and all are passed. It must be my code that is wrongly written. Adding this ( https://github.com/herpiko/machinery/commit/20b2e53986d083d747f2629799b64c7625c5e8fa ) solves my chain issue but it breaks the unit testing. Is there any clue what is wrong with the code above?

**Comment by RichardKnop** [comment]
@herpiko In a chain each task will append it's result to the next task in chain. So your second task's signature should have empty `Args` as the first task will pass its result as argument to next task. Also name of task needs to be the same as task registered by the worker so change name of second task to `build`.

```go
package main

import (
	"fmt"
	machinery "github.com/RichardKnop/machinery/v1"
	"github.com/RichardKnop/machinery/v1/config"
	"github.com/RichardKnop/machinery/v1/tasks"
	"time"
)

func main() {
	var conf = config.Config{
		Broker:        "amqp://guest:guest@localhost:5672/",
		ResultBackend: "amqp://guest:guest@localhost:5672/",
		DefaultQueue:  "irgsh_tasks",
		AMQP: &config.AMQPConfig{
			Exchange:     "machinery_exchange",
			ExchangeType: "direct",
			BindingKey:   "machinery_task",
		},
	}

	server, err := machinery.NewServer(&conf)
	if err != nil {
		fmt.Println("Could not create server : " + err.Error())
	}
	buildSignature := tasks.Signature{
		Name: "build",
		Args: []tasks.Arg{
			{
				Type:  "string",
				Value: "inkscape",
			},
		},
	}
	repoSignature := tasks.Signature{
		Name: "build",
                 // No Args here as buildSignature result will be passed to this task
	}
	fmt.Println("Sending task")
	chain, _ := tasks.NewChain(&buildSignature, &repoSignature)
	chainAsyncResult, err := server.SendChain(chain)
	if err != nil {
		fmt.Println("Could not create server : " + err.Error())
	}

	results, err := chainAsyncResult.Get(1 * time.Second)
	if err != nil {
		fmt.Println("Failed to get chain async result : " + err.Error())
	}
	for _, result := range results {
		fmt.Println(result.Interface())
	}
}
```
