### ISSUE TITLE
Failing to specify a ResultBackend should not panic

### ISSUE THREAD

**Issue by liftM** [RichardKnop/machinery#389]
This is related to #27.

Failing to set a `ResultBackend` in the configuration causes a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xa88876]

goroutine 24357 [running]:
<project>/vendor/github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc0000aef50, 0xc0002af110, 0x0, 0x0)
	/go/src/<project>/vendor/github.com/RichardKnop/machinery/v1/worker.go:133 +0xe6
<project>/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).consumeOne(0xc0001a80c0, 0xc0001ac140, 0x126, 0x126, 0xd89e40, 0xc0000aef50, 0x0, 0x0)
	/go/src/<project>/vendor/github.com/RichardKnop/machinery/v1/brokers/redis/redis.go:307 +0x23f
<project>/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).consume.func1(0xc0001a80c0, 0xc0001ac140, 0x126, 0x126, 0xd89e40, 0xc0000aef50, 0xc00009d1a0, 0x1, 0xc00008a900)
	/go/src/<project>/vendor/github.com/RichardKnop/machinery/v1/brokers/redis/redis.go:269 +0x67
created by <project>/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).consume
	/go/src/<project>/vendor/github.com/RichardKnop/machinery/v1/brokers/redis/redis.go:268 +0x106
```

This is because there is no nil checking of the result of `worker.server.GetBackend()` in line 133: https://github.com/RichardKnop/machinery/blob/22b2f6e64a9c04dd419391d42fc6d08201ce0d49/v1/worker.go#L133

Debugging this error is more confusing than it should be. Instead of needing users to chase down panics, calling `NewServer` without a `ResultBackend` should return an error.

**Comment by RichardKnop** [comment]
@liftM I agree. Do you want to make a PR to return a friendly error? Result backend is required for machinery to work actually as it needs to store task state somewhere. There is an `eager` backend which is basically just storing state in memory. You can use it locally for testing or running simple tasks if you don't care about keeping the state.
