### ISSUE TITLE
reflect: cannot use string as type []string in Call when returning string

### ISSUE THREAD

**Issue by LouAdrien** [RichardKnop/machinery#432]
Hello, I am trying to register a method that has to return a string. The method runs fine when not returning anything, but when changing it to return the string, I get a panic :

`

    func RunSimulator(inputDBForRun string) (string,error) {
        s:=Simulate()
        return s.runDatabaseName,nil
    }

`
`

sm.server.RegisterTask("simulate", RunSimulator)

`

> ERROR: 2019/07/02 19:14:07 task.go:130 goroutine 1510 [running]:
runtime/debug.Stack(0x2c3e788, 0xc0001e8080, 0x2)
	/Users/Lou/.go/src/runtime/debug/stack.go:24 +0x9d
simcel/vendor/github.com/RichardKnop/machinery/v1/tasks.(*Task).Call.func1(0xc00053f618, 0xc0004926e0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/tasks/task.go:130 +0xbc
panic(0x1cf0180, 0xc0003b6950)
	/Users/Lou/.go/src/runtime/panic.go:522 +0x1b5
reflect.Value.call(0x1d3bbe0, 0x1f6d540, 0x13, 0x1f1f873, 0x4, 0xc000095e00, 0x4, 0x4, 0xc00053f4a0, 0x10, ...)
	/Users/Lou/.go/src/reflect/value.go:388 +0x12cb
reflect.Value.Call(0x1d3bbe0, 0x1f6d540, 0x13, 0xc000095e00, 0x4, 0x4, 0x0, 0x1, 0x1)
	/Users/Lou/.go/src/reflect/value.go:308 +0xa4
simcel/vendor/github.com/RichardKnop/machinery/v1/tasks.(*Task).Call(0xc0004926e0, 0x0, 0x0, 0x0, 0x2220720, 0xc0003b6960)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/tasks/task.go:142 +0x246
simcel/vendor/github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc0000c4050, 0xc0003dd520, 0x0, 0x0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/worker.go:169 +0x3d9
simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consumeOne(0xc000463260, 0x223b260, 0xc00021e360, 0x0, 0xc000039e70, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:326 +0x62c
simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume.func2(0xc000463260, 0xc000112a00, 0x2227c20, 0xc0000c4050, 0xc000096720, 0x4, 0xc0000966c0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:278 +0xc2
created by simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:277 +0x133

ERROR: 2019/07/02 19:14:07 task.go:130 goroutine 1483 [running]:
runtime/debug.Stack(0x2c3e788, 0xc000476800, 0x2)
	/Users/Lou/.go/src/runtime/debug/stack.go:24 +0x9d
simcel/vendor/github.com/RichardKnop/machinery/v1/tasks.(*Task).Call.func1(0xc0002cf618, 0xc0001eb5e0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/tasks/task.go:130 +0xbc
panic(0x1cf0180, 0xc0001df9d0)
	/Users/Lou/.go/src/runtime/panic.go:522 +0x1b5
reflect.Value.call(0x1d3bbe0, 0x1f6d540, 0x13, 0x1f1f873, 0x4, 0xc0000180c0, 0x4, 0x4, 0xc0002cf4a0, 0x10, ...)
	/Users/Lou/.go/src/reflect/value.go:388 +0x12cb
reflect.Value.Call(0x1d3bbe0, 0x1f6d540, 0x13, 0xc0000180c0, 0x4, 0x4, 0x0, 0x1, 0x1)
	/Users/Lou/.go/src/reflect/value.go:308 +0xa4
simcel/vendor/github.com/RichardKnop/machinery/v1/tasks.(*Task).Call(0xc0001eb5e0, 0x0, 0x0, 0x0, 0x2220720, 0xc0001df9e0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/tasks/task.go:142 +0x246
simcel/vendor/github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc0000c4050, 0xc0000dc4e0, 0x0, 0x0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/worker.go:169 +0x3d9
simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consumeOne(0xc000463260, 0x223b260, 0xc00021e360, 0x0, 0xc0002be2e0, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:326 +0x62c
simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume.func2(0xc000463260, 0xc0004ab400, 0x2227c20, 0xc0000c4050, 0xc000096720, 0x4, 0xc0000966c0)
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:278 +0xc2
created by simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume
	/Users/Lou/go/src/simcel/vendor/github.com/RichardKnop/machinery/v1/brokers/amqp/amqp.go:277 +0x133

panic: reflect: cannot use string as type []string in Call

Any idea why? Thanks in advance.

**Comment by LouAdrien** [comment]
This was due to the wrong param type in the handler function defined as handler of chords of this type of tasks. Sorry.
