### ISSUE TITLE
Multiple workers execute Quit() error

### ISSUE THREAD

**Issue by Liv1020** [RichardKnop/machinery#437]
panic: close of closed channel [recovered]
	panic: close of closed channel

**Comment by unkeep** [comment]
having same issue. to avoid it i set `NoUnixSignals: true` and then manually call `mchServer.GetBroker().StopConsuming()`. This gets the workers shutdown

**Comment by 13rac1** [comment]
Not sure if this is the correct/same panic. My redacted error log from similar error:
```
{"APP":{"level":"info","msg":"Stop channel","time":"2020-02-05T15:00:10-08:00"}}
{"APP":{"level":"info","msg":"Signal received: interrupt","time":"2020-02-05T15:00:10-08:00"}}
{"APP":{"level":"info","msg":"Waiting for running tasks to finish before shutting down","time":"2020-02-05T15:00:10-08:00"}}
panic: close of closed channel

goroutine 44 [running]:
github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/common.(*Broker).StopConsuming(0xc00046c0c0)
	/go/src/github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/common/broker.go:107 +0x63
github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/brokers/redis.(*Broker).StopConsuming(0xc00046c0c0)
	/go/src/github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/brokers/redis/redis.go:157 +0x2d
github.com/org/app/vendor/github.com/RichardKnop/machinery/v1.(*Worker).Quit(...)
	/go/src/github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/worker.go:117
github.com/org/app/vendor/github.com/RichardKnop/machinery/v1.(*Worker).LaunchAsync.func2.1(0xc0000f2000, 0xc0004561e0)
	/go/src/github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/worker.go:97 +0x3c
created by github.com/org/app/vendor/github.com/RichardKnop/machinery/v1.(*Worker).LaunchAsync.func2
	/go/src/github.com/org/app/vendor/github.com/RichardKnop/machinery/v1/worker.go:96 +0x181
```

First clue is  https://github.com/RichardKnop/machinery/commit/bc427bd7fe3267b8fc625c09c22e95ab2fee3338 from https://github.com/RichardKnop/machinery/pull/421

**Comment by 13rac1** [comment]
The application was running version 1.5.5 without problem. I performed a complete dependency upgrade which included Machinery to 1.7.3. The integration tests began to fail.

Version 1.6.4 is the latest version without the changes from #421. The tests complete successfully when version 1.6.4 is a hard requirement. I confirmed panic reproduction when running the tests with version 1.6.5 which includes 421 changes. This partial upgrade is acceptable for now, but I'd like to figure out what else is needed.
