### ISSUE TITLE
AMQP messages remain ready after being acked

### ISSUE THREAD

**Issue by willgorman** [RichardKnop/machinery#483]
I'm running into something unexpected where even after machinery processes and acks messages they are remaining in rabbitmq in a `ready` status.    I can observe this by running the example and then listing queues via `rabbitmqctl`:

### Worker ###

```
go run example/machinery.go -c example/config.yml worker
INFO: 2019/10/29 10:47:16 file.go:19 Successfully loaded config from file example/config.yml
INFO: 2019/10/29 10:47:16 worker.go:47 Launching a worker with the following settings:
INFO: 2019/10/29 10:47:16 worker.go:48 - Broker: amqp://guest:guest@localhost:5672/
INFO: 2019/10/29 10:47:16 worker.go:50 - DefaultQueue: machinery_tasks
INFO: 2019/10/29 10:47:16 worker.go:54 - ResultBackend: amqp://guest:guest@localhost:5672
INFO: 2019/10/29 10:47:16 worker.go:56 - AMQP: machinery_exchange
INFO: 2019/10/29 10:47:16 worker.go:57   - Exchange: machinery_exchange
INFO: 2019/10/29 10:47:16 worker.go:58   - ExchangeType: direct
INFO: 2019/10/29 10:47:16 worker.go:59   - BindingKey: machinery_task
INFO: 2019/10/29 10:47:16 worker.go:60   - PrefetchCount: 3
INFO: 2019/10/29 10:47:16 amqp.go:95 [*] Waiting for messages. To exit press CTRL+C
INFO: 2019/10/29 10:47:24 amqp.go:330 Received new message: {"UUID":"task_68ca222b-62b5-4705-8870-67ad7a36b8d2","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":1},{"Name":"","Type":"int64","Value":1}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:24 machinery.go:136  I am a start of task handler for: add 
DEBUG: 2019/10/29 10:47:24 worker.go:249 Processed task task_68ca222b-62b5-4705-8870-67ad7a36b8d2. Results = 2
INFO: 2019/10/29 10:47:24 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:24 amqp.go:330 Received new message: {"UUID":"task_8727f035-bd5b-4eda-a1de-e9de650b0dcd","Name":"sum_ints","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"[]int64","Value":[1,2]}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:24 machinery.go:136  I am a start of task handler for: sum_ints 
DEBUG: 2019/10/29 10:47:24 worker.go:249 Processed task task_8727f035-bd5b-4eda-a1de-e9de650b0dcd. Results = 3
INFO: 2019/10/29 10:47:24 machinery.go:140  I am an end of task handler for: sum_ints 
INFO: 2019/10/29 10:47:24 amqp.go:330 Received new message: {"UUID":"task_2b945d74-c281-43c2-b434-46480dc4d3f5","Name":"sum_floats","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"[]float64","Value":[1.5,2.7]}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:24 machinery.go:136  I am a start of task handler for: sum_floats 
DEBUG: 2019/10/29 10:47:24 worker.go:249 Processed task task_2b945d74-c281-43c2-b434-46480dc4d3f5. Results = 4.2
INFO: 2019/10/29 10:47:24 machinery.go:140  I am an end of task handler for: sum_floats 
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_9b844897-bab3-451c-bfcb-5898b68ee2be","Name":"concat","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"[]string","Value":["foo","bar"]}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: concat 
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_9b844897-bab3-451c-bfcb-5898b68ee2be. Results = foobar
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: concat 
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_991e0634-d5b0-494b-84ef-db611fee8649","Name":"split","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"string","Value":"foo"}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: split 
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_991e0634-d5b0-494b-84ef-db611fee8649. Results = [f o o]
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: split 
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_04e6f3d1-bf81-4d32-90b6-d5f610592aa7","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"group_50a7ec5b-4c01-4e76-b2e6-60bd7cd62d16","GroupTaskCount":3,"Args":[{"Name":"","Type":"int64","Value":5},{"Name":"","Type":"int64","Value":6}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_be70597d-f334-42fe-9f74-6b24ae808f3a","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"group_50a7ec5b-4c01-4e76-b2e6-60bd7cd62d16","GroupTaskCount":3,"Args":[{"Name":"","Type":"int64","Value":2},{"Name":"","Type":"int64","Value":2}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_fbad5982-98ff-409d-bc8d-f4f06f5fa271","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"group_50a7ec5b-4c01-4e76-b2e6-60bd7cd62d16","GroupTaskCount":3,"Args":[{"Name":"","Type":"int64","Value":1},{"Name":"","Type":"int64","Value":1}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_04e6f3d1-bf81-4d32-90b6-d5f610592aa7. Results = 11
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_be70597d-f334-42fe-9f74-6b24ae808f3a. Results = 4
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_fbad5982-98ff-409d-bc8d-f4f06f5fa271. Results = 2
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_b02241be-2b3f-4088-be73-33a1725665fa","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"group_035c5011-13c9-43ed-a169-1634232a94f5","GroupTaskCount":3,"Args":[{"Name":"","Type":"int64","Value":1},{"Name":"","Type":"int64","Value":1}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":{"UUID":"chord_aa7e5708-8ad8-4764-b90b-27df81c70364","Name":"multiply","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":null,"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false},"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_b23f83ac-2264-4900-8cab-e3ffcef1b939","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"group_035c5011-13c9-43ed-a169-1634232a94f5","GroupTaskCount":3,"Args":[{"Name":"","Type":"int64","Value":2},{"Name":"","Type":"int64","Value":2}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":{"UUID":"chord_aa7e5708-8ad8-4764-b90b-27df81c70364","Name":"multiply","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":null,"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false},"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_77ed1d86-f4d8-4163-9c99-b2160d277773","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"group_035c5011-13c9-43ed-a169-1634232a94f5","GroupTaskCount":3,"Args":[{"Name":"","Type":"int64","Value":5},{"Name":"","Type":"int64","Value":6}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":{"UUID":"chord_aa7e5708-8ad8-4764-b90b-27df81c70364","Name":"multiply","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":null,"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false},"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_b23f83ac-2264-4900-8cab-e3ffcef1b939. Results = 4
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_77ed1d86-f4d8-4163-9c99-b2160d277773. Results = 11
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task task_b02241be-2b3f-4088-be73-33a1725665fa. Results = 2
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"chord_aa7e5708-8ad8-4764-b90b-27df81c70364","Name":"multiply","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":4},{"Name":"","Type":"int64","Value":11},{"Name":"","Type":"int64","Value":2}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: multiply 
DEBUG: 2019/10/29 10:47:25 worker.go:249 Processed task chord_aa7e5708-8ad8-4764-b90b-27df81c70364. Results = 88
INFO: 2019/10/29 10:47:25 machinery.go:140  I am an end of task handler for: multiply 
INFO: 2019/10/29 10:47:25 amqp.go:330 Received new message: {"UUID":"task_7612392d-621f-4a6b-9e37-efc734fd37f3","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":1},{"Name":"","Type":"int64","Value":1}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_f0d546ab-46b7-4cc8-8a61-ba395ac7f8a8","Name":"add","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":2},{"Name":"","Type":"int64","Value":2}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_816fd91f-a4d7-43b4-b0da-7d0ea0fd7c3f","Name":"add","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":5},{"Name":"","Type":"int64","Value":6}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_b6dfb69d-34c1-4d5c-81c0-b152bb90bb31","Name":"multiply","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":4}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}],"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}],"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}],"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:25 machinery.go:136  I am a start of task handler for: add 
DEBUG: 2019/10/29 10:47:26 worker.go:249 Processed task task_7612392d-621f-4a6b-9e37-efc734fd37f3. Results = 2
INFO: 2019/10/29 10:47:26 amqp.go:330 Received new message: {"UUID":"task_f0d546ab-46b7-4cc8-8a61-ba395ac7f8a8","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":2},{"Name":"","Type":"int64","Value":2},{"Name":"","Type":"int64","Value":2}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_816fd91f-a4d7-43b4-b0da-7d0ea0fd7c3f","Name":"add","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":5},{"Name":"","Type":"int64","Value":6}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_b6dfb69d-34c1-4d5c-81c0-b152bb90bb31","Name":"multiply","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":4}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}],"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}],"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:26 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:26 machinery.go:136  I am a start of task handler for: add 
DEBUG: 2019/10/29 10:47:26 worker.go:249 Processed task task_f0d546ab-46b7-4cc8-8a61-ba395ac7f8a8. Results = 6
INFO: 2019/10/29 10:47:26 amqp.go:330 Received new message: {"UUID":"task_816fd91f-a4d7-43b4-b0da-7d0ea0fd7c3f","Name":"add","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":5},{"Name":"","Type":"int64","Value":6},{"Name":"","Type":"int64","Value":6}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":[{"UUID":"task_b6dfb69d-34c1-4d5c-81c0-b152bb90bb31","Name":"multiply","RoutingKey":"","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":4}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}],"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:26 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:26 machinery.go:136  I am a start of task handler for: add 
DEBUG: 2019/10/29 10:47:26 worker.go:249 Processed task task_816fd91f-a4d7-43b4-b0da-7d0ea0fd7c3f. Results = 17
INFO: 2019/10/29 10:47:26 amqp.go:330 Received new message: {"UUID":"task_b6dfb69d-34c1-4d5c-81c0-b152bb90bb31","Name":"multiply","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"int64","Value":4},{"Name":"","Type":"int64","Value":17}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:26 machinery.go:140  I am an end of task handler for: add 
INFO: 2019/10/29 10:47:26 machinery.go:136  I am a start of task handler for: multiply 
DEBUG: 2019/10/29 10:47:26 worker.go:249 Processed task task_b6dfb69d-34c1-4d5c-81c0-b152bb90bb31. Results = 68
INFO: 2019/10/29 10:47:26 machinery.go:140  I am an end of task handler for: multiply 
INFO: 2019/10/29 10:47:26 amqp.go:330 Received new message: {"UUID":"task_229bf94f-1091-4721-8f02-ad9334f6f031","Name":"panic_task","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":null,"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:26 machinery.go:136  I am a start of task handler for: panic_task 
ERROR: 2019/10/29 10:47:26 task.go:130 goroutine 580 [running]:
runtime/debug.Stack(0x2571c60, 0xc000136b00, 0x2)
        /Users/will.gorman/.gimme/versions/go1.13.1.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call.func1(0xc0004d7628, 0xc0000ed1d0)
        /Users/will.gorman/git/machinery/v1/tasks/task.go:130 +0xbc
panic(0x1a41e00, 0xc000224d30)
        /Users/will.gorman/.gimme/versions/go1.13.1.darwin.amd64/src/runtime/panic.go:679 +0x1b2
github.com/RichardKnop/machinery/example/tasks.PanicTask(0x0, 0x0, 0x0, 0x0)
        /Users/will.gorman/git/machinery/example/tasks/tasks.go:63 +0x59
reflect.Value.call(0x1a00ba0, 0x1bdb4a8, 0x13, 0x1b9c69c, 0x4, 0x2571c60, 0x0, 0x0, 0x1afab40, 0x1b4b580, ...)
        /Users/will.gorman/.gimme/versions/go1.13.1.darwin.amd64/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1a00ba0, 0x1bdb4a8, 0x13, 0x2571c60, 0x0, 0x0, 0xc00028a730, 0xc000102900, 0x65)
        /Users/will.gorman/.gimme/versions/go1.13.1.darwin.amd64/src/reflect/value.go:321 +0xb4
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call(0xc0000ed1d0, 0x0, 0x0, 0x0, 0x1e56aa0, 0xc000224d30)
        /Users/will.gorman/git/machinery/v1/tasks/task.go:142 +0x25d
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc00028ad20, 0xc0003c20f0, 0x0, 0x0)
        /Users/will.gorman/git/machinery/v1/worker.go:170 +0x389
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consumeOne(0xc000421730, 0x1e67e40, 0xc0000f17a0, 0x0, 0xc000298640, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
        /Users/will.gorman/git/machinery/v1/brokers/amqp/amqp.go:332 +0x674
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume.func2(0xc000421730, 0xc00049ea00, 0x1e5e380, 0xc00028ad20, 0xc0004ce060, 0x0, 0xc0004ce000)
        /Users/will.gorman/git/machinery/v1/brokers/amqp/amqp.go:282 +0xc2
created by github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume
        /Users/will.gorman/git/machinery/v1/brokers/amqp/amqp.go:281 +0x133

ERROR: 2019/10/29 10:47:26 machinery.go:132  I am an error handler: oops 
INFO: 2019/10/29 10:47:26 machinery.go:140  I am an end of task handler for: panic_task 
INFO: 2019/10/29 10:47:26 amqp.go:330 Received new message: {"UUID":"task_c688fe78-1c99-4307-892d-cbb6cd3f3e8a","Name":"long_running_task","RoutingKey":"machinery_task","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":null,"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
INFO: 2019/10/29 10:47:26 machinery.go:136  I am a start of task handler for: long_running_task 
INFO: 2019/10/29 10:47:26 tasks.go:68 Long running task started
INFO: 2019/10/29 10:47:26 tasks.go:70 10
INFO: 2019/10/29 10:47:27 tasks.go:70 9
INFO: 2019/10/29 10:47:28 tasks.go:70 8
INFO: 2019/10/29 10:47:29 tasks.go:70 7
INFO: 2019/10/29 10:47:30 tasks.go:70 6
INFO: 2019/10/29 10:47:31 tasks.go:70 5
INFO: 2019/10/29 10:47:32 tasks.go:70 4
INFO: 2019/10/29 10:47:33 tasks.go:70 3
INFO: 2019/10/29 10:47:34 tasks.go:70 2
INFO: 2019/10/29 10:47:35 tasks.go:70 1
INFO: 2019/10/29 10:47:36 tasks.go:73 Long running task finished
DEBUG: 2019/10/29 10:47:36 worker.go:249 Processed task task_c688fe78-1c99-4307-892d-cbb6cd3f3e8a. Results = []
INFO: 2019/10/29 10:47:36 machinery.go:140  I am an end of task handler for: long_running_task 
```

### Sender ###

```
go run example/machinery.go -c example/config.yml send
INFO: 2019/10/29 10:47:24 file.go:19 Successfully loaded config from file example/co
nfig.yml
INFO: 2019/10/29 10:47:24 machinery.go:288  Starting batch: 318ee8e8-7d35-498d-8efc-
f40767fd7a4e 
INFO: 2019/10/29 10:47:24 machinery.go:294  Single task: 
INFO: 2019/10/29 10:47:24 machinery.go:305 1 + 1 = 2

INFO: 2019/10/29 10:47:24 machinery.go:319 sum([1, 2]) = 3

INFO: 2019/10/29 10:47:24 machinery.go:330 sum([1.5, 2.7]) = 4.2

INFO: 2019/10/29 10:47:25 machinery.go:341 concat(["foo", "bar"]) = foobar

INFO: 2019/10/29 10:47:25 machinery.go:352 split(["foo"]) = [f o o]

INFO: 2019/10/29 10:47:25 machinery.go:360  Group of tasks (parallel execution): 
INFO: 2019/10/29 10:47:25 machinery.go:377 1 + 1 = 2

INFO: 2019/10/29 10:47:25 machinery.go:377 2 + 2 = 4

INFO: 2019/10/29 10:47:25 machinery.go:377 5 + 6 = 11

INFO: 2019/10/29 10:47:25 machinery.go:387  Group of tasks with a callback (chord): 
INFO: 2019/10/29 10:47:25 machinery.go:408 (1 + 1) * (2 + 2) * (5 + 6) = 88

INFO: 2019/10/29 10:47:25 machinery.go:412  Chain of tasks: 
INFO: 2019/10/29 10:47:26 machinery.go:428 (((1 + 1) + (2 + 2)) + (5 + 6)) * 4 = 68

INFO: 2019/10/29 10:47:26 machinery.go:441 Task panicked and returned error = oops

INFO: 2019/10/29 10:47:36 machinery.go:454 Long running task returned = []
```

### Rabbitmqctl ###

```
docker exec -it rabbitmq rabbitmqctl list_queues name messages_ready messages_unacknowledged consumers
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name    messages_ready  messages_unacknowledged consumers
chord_aa7e5708-8ad8-4764-b90b-27df81c70364      0       0       0
task_b02241be-2b3f-4088-be73-33a1725665fa       0       0       0
task_f0d546ab-46b7-4cc8-8a61-ba395ac7f8a8       0       0       0
machinery_task  18      0       0
task_991e0634-d5b0-494b-84ef-db611fee8649       0       0       0
task_fbad5982-98ff-409d-bc8d-f4f06f5fa271       0       0       0
task_8727f035-bd5b-4eda-a1de-e9de650b0dcd       0       0       0
task_77ed1d86-f4d8-4163-9c99-b2160d277773       0       0       0
task_be70597d-f334-42fe-9f74-6b24ae808f3a       0       0       0
task_9b844897-bab3-451c-bfcb-5898b68ee2be       0       0       0
machinery_tasks 0       0       1
task_229bf94f-1091-4721-8f02-ad9334f6f031       0       0       0
task_b6dfb69d-34c1-4d5c-81c0-b152bb90bb31       0       0       0
task_b23f83ac-2264-4900-8cab-e3ffcef1b939       0       0       0
task_7612392d-621f-4a6b-9e37-efc734fd37f3       0       0       0
task_68ca222b-62b5-4705-8870-67ad7a36b8d2       0       0       0
nbs_task_queue  0       0       0
task_c688fe78-1c99-4307-892d-cbb6cd3f3e8a       0       0       0
task_816fd91f-a4d7-43b4-b0da-7d0ea0fd7c3f       0       0       0
task_2b945d74-c281-43c2-b434-46480dc4d3f5       0       0       0
task_04e6f3d1-bf81-4d32-90b6-d5f610592aa7       0       0       0
```

The machinery_task queue has 18 ready messages after everything has been processed and acked, and if I keep running the example the number of ready messages keeps increasing.  Machinery never processes those ready messages but I can confirm they are there via the rabbitmq management UI.  I'm using the `rabbitmq:3-management` docker image which is currently `3.8.0`.  

Is this something anyone else has seen?

**Comment by jkamdjou** [comment]
We're experiencing this same exact issue. Were you ever able to resolve it?

**Comment by jkamdjou** [comment]
We worked around the issue by using Redis as the results backend instead of AMQP.

**Comment by vtfr** [comment]
Any update on this issue?
