### ISSUE TITLE
[Question] Calling Task without server

### ISSUE THREAD

**Issue by tarunwadhwa13** [RichardKnop/machinery#563]
Is it possible to trigger a task without using machinery worker? The JSON mentioned in the README docs was pushed as is to a Rabbitmq queue but worker is raising null pointer exceptions while executing the tasks !!

**Comment by charleswhchan** [comment]
If I understand your question: you want to be able to test your task without invoking queue/worker?

Since [tasks](https://github.com/RichardKnop/machinery#tasks) are just defined as regular functions, they call be called directly as well to test/debug the implementation. This might help you isolate issues with [Registration](https://github.com/RichardKnop/machinery#registering-tasks),  [Signatures](https://github.com/RichardKnop/machinery#signatures), or [Sending Tasks](https://github.com/RichardKnop/machinery#sending-tasks).

Using `Add` task as an example:
```
func Add(args ...int64) (int64, error) {
  sum := int64(0)
  for _, arg := range args {
    sum += arg
  }
  return sum, nil
}
```

You can call it directly:
```
result, err := Add(1, 2)
```

**Comment by tarunwadhwa13** [comment]
Thanks for the reply :) but it isn't about testing !!

We have a golang application with machinery workers running for processing all the events generated. Events are actually present in a RabbitMQ. The producers generating events are NOT in golang hence cant implement machinery servers.
Producers just dump the event in RMQ in a specified format !!

Wanted to understand if it's possible to create a system wherein the task gets scheduled as soon a JSON in particular format is added to the queue?

If yes, what should be the format and datatype?

We are adding the json from Readme example as string in Rabbitmq queue. The worker reads the message but raises segmentation faults

**Comment by charleswhchan** [comment]
I see what you mean. Interesting concept. Unfortunately it is not something I had experience with.

Comparing the JSON format in the README against [tasks.Signature](https://github.com/RichardKnop/machinery/blame/master/v1/tasks/signature.go), I can see newer changes in the struct. I suspect the README might not be the most up to date.

You might want to have a look at https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L186. I can see it call `json.Marshal(signature)`, so you could write a small golang server to publish a small task to print out the exact message + format being published to the queue.

**Comment by tarunwadhwa13** [comment]
Thanks for the quick response @charleswhchan 
I tried creating a machinery server to check the JSON packet created. Strangely, machinery worker is giving segmentation fault even for message created by machinery server which certainly means that there is some issue in my setup instead.

1) The task gets registered successully
2) Task is received by the worker and worker prints "Received New Message" Log (https://github.com/RichardKnop/machinery/blob/v1.8.5/v1/brokers/amqp/amqp.go#L335)
3) But seems like the signature object created by the worker has some issues as it fails in worker.Process method
https://github.com/RichardKnop/machinery/blob/v1.8.5/v1/worker.go#L135

```
DEBUG: 2020/06/08 10:57:23 amqp.go:335 Received new message: {"UUID":"task_fec3ede3-27f3-4dbe-bd27-08455af5e5b8","Name":"UpsertRecord","RoutingKey":"feed_orient","ETA":null,"GroupUUID":"","GroupTaskCount":0,"Args":[{"Name":"","Type":"string","Value":"ASG"},{"Name":"","Type":"string","Value":"2020-10-05 06:06:30"},{"Name":"","Type":"string","Value":"dummy"}],"Headers":{},"Priority":0,"Immutable":false,"RetryCount":0,"RetryTimeout":0,"OnSuccess":null,"OnError":null,"ChordCallback":null,"BrokerMessageGroupId":"","SQSReceiptHandle":"","StopTaskDeletionOnError":false,"IgnoreWhenTaskNotRegistered":false}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xfaed96]

goroutine 24 [running]:
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc000362b40, 0xc0004fe000, 0x0, 0x0)
	/home/tarunw/go/pkg/mod/github.com/!richard!knop/machinery@v1.8.5/v1/worker.go:148 +0xe6
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consumeOne(0xc0004ce540, 0x1615fc0, 0xc0004fa000, 0x0, 0xc00030e220, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	/home/tarunw/go/pkg/mod/github.com/!richard!knop/machinery@v1.8.5/v1/brokers/amqp/amqp.go:337 +0x4f4
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume.func2(0xc0004ce540, 0xc0003183c0, 0x1614a40, 0xc000362b40, 0xc0002b06c0, 0xa, 0xc0002fe3c0)
	/home/tarunw/go/pkg/mod/github.com/!richard!knop/machinery@v1.8.5/v1/brokers/amqp/amqp.go:287 +0xca
created by github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume
	/home/tarunw/go/pkg/mod/github.com/!richard!knop/machinery@v1.8.5/v1/brokers/amqp/amqp.go:286 +0x133
exit status 2
```
